"""Renombrar tabla attendance_records a attendance

Revision ID: 9740d2772b69
Revises: e142cab43594
Create Date: 2025-10-25 04:31:02.910137

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9740d2772b69"
down_revision: Union[str, Sequence[str], None] = "e142cab43594"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
